apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: django-rs
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: 870165402940.dkr.ecr.us-east-1.amazonaws.com/django-pipeline:latest
